### ISSUE TITLE
Is the latest build in Cydia? and how to enable GET_TASK_ALLOW?

### ISSUE THREAD

**Issue by aaronash** [sbingner/jbctl#5]
Total newb question ;)
I'd like to be able to attach to any process (enable GET_TASK_ALLOW). I downloaded the version from Cydia and ran `jbctl -u GET_TASK_ALLOW=1` (might not even be correct), but it seems the Cydia .deb doesn't have the -u option?

I attempted to setup Coolstar's toolchain on device to compile it from source, but was not able to get it fully setup.

Thanks!
Aaron

**Comment by sbingner** [comment]
That is jailbreak specific - -u works with unc0ver but not checkra1n.  You also can’t disable that on A12 unc0ver.

**Comment by armfc6161** [comment]
> Total newb question ;)
> I'd like to be able to attach to any process (enable GET_TASK_ALLOW). I downloaded the version from Cydia and ran `jbctl -u GET_TASK_ALLOW=1` (might not even be correct), but it seems the Cydia .deb doesn't have the -u option?
> 
> I attempted to setup Coolstar's toolchain on device to compile it from source, but was not able to get it fully setup.
> 
> Thanks!
> Aaron
